config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'landing_page#index'
  #get '/jogadores', to: 'players#index'

  #get '/teams', to: 'teams#index'
  #get '/teams/:id', to: 'teams#show'
  resources :teams, only: [:index, :show], path: "times" do
    collection do
      get :comparison
    end
  end
  get 'teams/search', to: 'teams#search'

 

  resources :players, only: [:index, :show], path: "jogadores" do
    collection do
      get :comparison
    end
  end

  get 'players/search', to: 'players#search'
  #resources :players, path: "jogadores"
  
  
end

app/models/player.rb
class Player < ApplicationRecord
    belongs_to :team
    has_one :player_stat
    delegate :two_pointers_percentage, to: :player_stat
    delegate :three_pointers_percentage, to: :player_stat
    delegate :assists_percentage, to: :player_stat
    delegate :blocks_percentage, to: :player_stat
    delegate :free_throws_percentage, to: :player_stat
    delegate :steals_percentage, to: :player_stat
    delegate :field_goals_percentage, to: :player_stat
    delegate :player_efficiency_rating, to: :player_stat
    delegate :turn_overs_percentage, to: :player_stat
    delegate :true_shooting_percentage, to: :player_stat
    delegate :usage_rate_percentage, to: :player_stat
    delegate :turn_overs_percentage, to: :player_stat
    delegate :effective_field_goals_percentage, to: :player_stat
    delegate :total_rebounds_percentage, to: :player_stat
    ransack_alias :team, :team_name

    paginates_per 12

    def self.biggest_score_at(stat)
        joins(:player_stat)
            .order(stat => :desc)
            .first  
    end

    ransacker :full_name do |parent|
        Arel::Nodes::NamedFunction.new('CONCAT_WS', [
           Arel::Nodes.build_quoted(' '), parent.table[:first_name], parent.table[:last_name]
        ])   
    end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
    before_action :force_json, only: :search
    #GET /players
    def index
       @q = Player.ransack(params[:q])
       @players = @q.result.order(:first_name).page(params[:page])

    end

    def show
        @player = Player.find(params[:id])
    end

    def comparison
        @player1 = Player.find(params[:first_player])
        @player2 = Player.find(params[:second_player])
    end

    def search
        q = params[:q].downcase
        @players = Player.where("first_name ILIKE ? or last_name ILIKE ?", "%#{q}%", "%#{q}%").limit(5)
    end

    def force_json
        request.format = :json
    end

end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/comparison.html.erb
<section class="container comparison">
<div class="d-table-cell w-100 comparison-vertical-align">
<% if @player1.player_stat && @player2.player_stat %>
    <h2 class="name mb-5"><%=@player1.first_name%> <%=@player1.last_name%> vs <%=@player2.first_name%> <%=@player2.last_name%></h2>

    <div class="d-inline-flex w-100 justify-content-between mb-2">
        <h3><%= @player1.field_goals_percentage %>%</h3>
        <h2> Gols de campo </h2>
        <h3><%= @player2.field_goals_percentage %>%</h3>
    </div>

    <div class="d-inline-flex w-100 justify-content-between mb-2">
        <h3><%=@player1.two_pointers_percentage%>%</h3>
        <h2> Gols de dois pontos </h2>
        <h3><%= @player2.two_pointers_percentage %>%</h3>
    </div>

    <div class="d-inline-flex w-100 justify-content-between mb-2">
        <h3><%= @player1.three_pointers_percentage %>%</h3>
        <h2> Gols de tres pontos </h2>
        <h3><%= @player2.three_pointers_percentage %>%</h3>
    </div>

    <div class="d-inline-flex w-100 justify-content-between mb-2">
        <h3><%= @player1.free_throws_percentage %>%</h3>
        <h2> Lances livres </h2>
        <h3><%= @player2.free_throws_percentage %>%</h3>
    </div>
    <div class="d-inline-flex w-100 justify-content-between mb-2">
        <h3><%= @player1.total_rebounds_percentage %>%</h3>
        <h2> Rebotes </h2>
        <h3><%= @player2.total_rebounds_percentage %>%</h3>
    </div>
    <div class="d-inline-flex w-100 justify-content-between mb-2">
        <h3><%= @player1.true_shooting_percentage %>%</h3>
        <h2> Acertos na cesta </h2>
        <h3><%= @player2.true_shooting_percentage %>%</h3>
    </div>
    <div class="d-inline-flex w-100 justify-content-between mb-2">
        <h3><%= @player1.player_efficiency_rating %>%</h3>
        <h2> Taxa de eficiência </h2>
        <h3><%= @player2.player_efficiency_rating %>%</h3>
    </div>
    <div class="d-inline-flex w-100 justify-content-between mb-2">
        <h3><%= @player1.assists_percentage %>%</h3>
        <h2> Assistencias </h2>
        <h3><%= @player2.assists_percentage %>%</h3>
    </div>
    <div class="d-inline-flex w-100 justify-content-between mb-2">
        <h3><%= @player1.steals_percentage %>%</h3>
        <h2> Roubos de bola </h2>
        <h3><%= @player2.steals_percentage %>%</h3>
    </div>
    <div class="d-inline-flex w-100 justify-content-between mb-2">
        <h3><%= @player1.blocks_percentage %>%</h3>
        <h2> Bloqueios </h2>
        <h3><%= @player2.blocks_percentage %>%</h3>
    </div>
    <div class="d-inline-flex w-100 justify-content-between mb-2">
        <h3><%= @player1.turn_overs_percentage %>%</h3>
        <h2> Erros de Passe </h2>
        <h3><%= @player2.turn_overs_percentage %>%</h3>
    </div>
    <div class="d-inline-flex w-100 justify-content-between mb-2">
        <h3><%= @player1.usage_rate_percentage %>%</h3>
        <h2> Taxa de uso </h2>
        <h3><%= @player2.usage_rate_percentage %>%</h3>
    </div>

<% else %>
    <h2 class="name">Infelizmente alguns dos players não tem status para serem exibidos, ficando impossível a comparação</h2>
<%end%>
</div>
</section>

app/views/players/index.html.erb
<section class="container p-4 team-players " id="team ">
  <%= search_form_for @q do |f| %>
    <div class="search-border">
      <div class="input-group">
        <%= f.search_field :full_name_or_first_name_or_last_name_or_team_name_cont, placeholder: "Pesquisar", id: 'search_player', data: { behavior: "autocompletePlayers" } %>
        <div class="input-group-append">
          <%= button_tag( :class => "button_green") do %>
            <i class="fa fa-search"></i>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>

<div class="d-flex justify-content-end">
  <%= form_with(url: comparison_players_path, method: :get, local: true, class:"comparison-form") do %>
    <div class="search-border">
      <div class="input-group">
        <input type="search" placeholder="Nome" id="first_player" data-behavior="autocompletePlayers">
      </div>
    </div>
    <h2> Vs </h2>
    <div class="search-border">
      <div class="input-group">
        <input type="search" placeholder="Nome" id="second_player" data-behavior="autocompletePlayers ">
        <input type="hidden" name="first_player" id="hidden_first_player">
        <input type="hidden" name="second_player" id ="hidden_second_player" class="">
        <div class="input-group-append">
          <%= button_tag( :class => "button_green") do %>
            <i class="fa fa-search"></i>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<h2 class="d-none d-sm-block mt-3 text-right">Jogadores</h2>
<h2 class="d-sm-none mt-3 text-center">Jogadores</h2>

 <div class="mb-2 d-none d-sm-block", style="">
        <% @players.each do |player| %>
        
            <%= link_to player_path(player), :action => 'go' do %>
                <div class="row mt-5" style="border-left: 5px solid var(--dark-light); border-bottom: 5px solid var(--dark-light)">
                    <div class="col-7 row"  style="background: var(--primary); " > 
                        <div class="col-2" >
                            <%= image_tag("#{player.photo_url}", class:"rounded player-photo ") %>
                        </div>
                        <div class="col-2" style="display: flex; align-items: center; justify-content: center" >
                            <p style="color: var(--constrast-dark-light); font-size: 45px; font-family: Basketball; 
                            border-right: 3px solid var(--dark-light); 
                            padding-right: 15px"><%= player.jersey%></p>
                        </div>
                        <div class="col h-100 ml-2 name-position" >
                            <div class="d-table-cell ">
                                <p style="color: var(--constrast-dark-light); font-size: 20px; text-transform: uppercase" class="d-block"><%= player.first_name%> <%= player.last_name%></p>
                                <p style="color: var(--constrast-dark-light); font-size: 15px; margin-top: 5px"><%= position_to_br(player.position) %> pelo <%= player.team.name%></p>
                            </div>
                        </div>
                    </div>
                    <div class="col row"  style="background: var(--constrast-dark-light); " > 
                        <div class="col team-player-stats h-100" >
                            <div class="d-table-cell" style="text-align: center">
                            <% if player.player_stat %>
                                <p style="color: var(--dark-light); font-size: 20px; text-transform: uppercase" class="d-block"><%= player.player_stat&.free_throws_percentage %>%</p>
                                <p style="color: var(--dark-light); font-size: 15px; margin-top: 5px">Lances Livre</p>
                            <% else %>
                                <p style="color: var(--dark-light); font-size: 20px;">---</p>
                            <% end %>
                            </div>
                        </div>
                        <div class="col team-player-stats h-100" >
                            <div class="d-table-cell" style="text-align: center">
                            <% if player.player_stat %>
                                <p style="color: var(--dark-light); font-size: 20px; text-transform: uppercase" class="d-block"><%= player.player_stat&.player_efficiency_rating %>%</p>
                                <p style="color: var(--dark-light); font-size: 15px; margin-top: 5px">Taxa de Eficiência</p>
                            <% else %>
                                <p style="color: var(--dark-light); font-size: 20px;">---</p>
                            <% end %>
                            </div>
                        </div>
                        <div class="col team-player-stats h-100">
                            <div class="col d-table-cell" style="text-align: center">
                            <% if player.player_stat %>
                                <p style="color: var(--dark-light); font-size: 20px; text-transform: uppercase" class="d-block"><%= player.player_stat&.field_goals_percentage %>%</p>
                                <p style="color: var(--dark-light); font-size: 15px; margin-top: 5px">Cestas de Campo</p>
                            <% else %>
                                <p style="color: var(--dark-light); font-size: 20px;">---</p>
                            <% end %>
                            </div>
                        </div>
                    </div>
                </div>
            <% end %>
        <% end %>
    </div>

    <div class="mb-2 d-sm-none", style="display: flex;
    flex-wrap: wrap;
    justify-content: center;">
        <% @players.each do |player| %>
        
            <%= link_to player_path(player), :action => 'go' do %>
                <div class="card mt-5 mr-4 ml-4 mb-4" style="width: 15rem;">
                    <div class="d-inline-flex justify-content-end">
                    <%= image_tag("#{player.photo_url}", class:"rounded player-photo card-img-top", style:"margin-right: 0px") %>
                    <%= image_tag("#{player.team.wikipedia_logo_url}", class:"rounded player-photo card-img-top", style:"height: 68px; width: 68px !important; margin-top: 10px; margin-right: 10px; margin-left: 0px") %>
                    </div>
                    <div class="card-body ">
                        <h3 class="card-title" style="font-size: 35px"><%= player.first_name %> <%= player.last_name %> </h3>
                        <h2 class="card-text" style="color: #<%=player.team.primary_color%>"> <%= player.jersey%></h2>
                        <p class="card-text"><%= position_to_br(player.position) %> pelo <span style="color: #<%=player.team.primary_color %>"><%=player.team.name %></span></p>
                        <% if player.player_stat %>
                            <p>Lances Livre: <%= player.player_stat&.free_throws_percentage %>%</p>
                            <p>Cestas de Campo: <%= player.player_stat&.field_goals_percentage%>%</p>
                            <p>Taxa de eficiência: <%= player.player_stat&.player_efficiency_rating %>%</p>
                        <% else %>
                            <p>Jogos: ---</p>
                            <p>Cestas de Campo: ---</p>
                            <p>Lances Livre: ---</p>
                        <% end %>
                    </div>
                </div>
            <% end %>
        <% end %>
    </div>

</section>
<%= paginate @players, window: 1, left: 1, right: 1%>

app/views/players/show.html.erb
<script>

  $( document ).ready(function(){
     team_color = "#" + "<%= @player.team.primary_color %>" ;
     console.log(team_color);
     document.documentElement.style.setProperty('--primary', team_color);
     
 });  
</script>
<section id="player">
    <div class="container">
        <div class="player-main">
            <div class="d-inline-flex">
                <div class="player-name">
                    <h2><%= @player.last_name %></h2>
                    <h2><%= @player.first_name %></h2>
                    <%= image_tag("#{@player.photo_url}", class:"img-responsive rounded player-photo") %>
                </div>
                <h2 class="player-number"><%= @player.jersey%></h2>
                
            </div>
        </div>

        <div class="player-main-sm">
            <% if @player.jersey.present? %>
                <h2 class="player-number"><%= @player.jersey%></h2>
            <% else %>
                <h2 class="player-number">--</h2>
            <% end %>
            <div class="d-inline-flex w-100">
                <div class="player-name d-inline-flex">
                    <div class="d-block">
                        <h2><%= @player.last_name %></h2>
                        <h2><%= @player.first_name %></h2>
                    </div>
                    <%= image_tag("#{@player.photo_url}", class:"img-responsive rounded player-photo") %>
                </div>
                
                
            </div>
        </div>


        <div class="team-text">
            <%= image_tag("#{@player.team.wikipedia_logo_url}", class:"img-responsive") %>
            <p class="about-player"><%=@player.first_name%> <%=@player.last_name %> atualmente no
             time <span style="color: var(--primary)">
            <%=@player.team.name %></span> como <%= position_to_br(@player.position) %>, joga na NBA há <%= @player.experience %> anos.
            <% if @player.birth_city and @player.birth_date %>
             Nasceu no <%= date_to_br(@player&.birth_date)%> em 
             <%=@player&.birth_city %>, <%=@player&.birth_state%></p>
             <%# image_tag("#{@player.photo_url}", class:"img-responsive ml-4 rounded") %>
             <% end %>
        </div>
    </div>
</section>

<section class="show-info container mt-4 mb-4">
<div class="div-show-info center">
<h2>Dados</h2>
<div class="w-100 d-inline-flex flex-row-reverse align-items-center mt-4 justify-content-start">
    <h4><%=@player.jersey%></h4>
    <%= image_tag("#{@player.photo_url}", class:"img-responsive rounded ", style:"height: 95px") %>
</div>
<p style="clear: right"><%= @player.first_name %> <%= @player.last_name%></p>
<p>Do time <%=@player.team.name %></p>
<p><%= position_to_br(@player.position) %></p>
<% if @player.birth_city %>
    <p>Nascido em <%=@player&.birth_city%> - <%= @player.birth_state%></p>
<% else %>
    <p>Nascido em ?? </p>
<%end%>
<% if @player.birth_date %>
    <p> <%date_to_br(@player&.birth_date)%> </p>
<% else %>
    <p> 99/99/9999 </p>
<% end %>
<p>Salário de R$<%= number_with_delimiter(@player.salary, :delimiter => '.')%> </p>


<% if @player.player_stat %>
<div class="graph-flex">
    
    <div style="" class="graph-display">
        <h3>Dois pontos %</h3>
        <div style="", class="graph-and-text">
        <%= pie_chart([
            {name: "Sucesso", data: @player.two_pointers_percentage.to_f},
            {name: "Falha", data: (100 - @player.two_pointers_percentage.to_f)},
            ], legend: "left", colors:['#252525', '#3d0000', '#9C27B0']) %>
        </div>
    </div>

    <div style="" class="graph-display">
        <h3>Tres pontos %</h3>
        <div style="", class="graph-and-text">
        <%= pie_chart([
            {name: "Sucesso", data: @player.three_pointers_percentage.to_f},
            {name: "Falhados", data: (100 - @player.three_pointers_percentage.to_f)},
            ], legend: "left", colors:['#252525', '#3d0000', '#9C27B0']) %>
        </div>
    </div>

    <div style="" class="graph-display">
        <h3>Assistencia %</h3>
        <div style="", class="graph-and-text">
        <%= pie_chart([
            {name: "Sucesso", data: @player.assists_percentage.to_f},
            {name: "Falhados", data: (100 - @player.assists_percentage.to_f)},
            ], legend: "left", colors:['#252525', '#3d0000', '#9C27B0']) %>
        </div>
    </div>

    <div style="" class="graph-display">
        <h3>Bloqueio %</h3>
        <div style="", class="graph-and-text">
        <%= pie_chart([
            {name: "Sucesso", data: @player.blocks_percentage.to_f},
            {name: "Falhados", data: (100 - @player.blocks_percentage.to_f)},
            ], legend: "left", colors:['#252525', '#3d0000', '#9C27B0']) %>
        </div>
    </div>

    <div style="" class="graph-display">
        <h3>Lance Livre %</h3>
        <div style="", class="graph-and-text">
        <%= pie_chart([
            {name: "Sucesso", data: @player.free_throws_percentage.to_f},
            {name: "Falhados", data: (100 - @player.free_throws_percentage.to_f)},
            ], legend: "left", colors:['#252525', '#3d0000', '#9C27B0']) %>
        </div>
    </div>

    <div style="" class="graph-display">
        <h3>Roubo de Bola %</h3>
        <div style="", class="graph-and-text">
        <%= pie_chart([
            {name: "Sucesso", data: @player.steals_percentage.to_f},
            {name: "Falhados", data: (100 - @player.steals_percentage.to_f)},
            ], legend: "left", colors:['#252525', '#3d0000', '#9C27B0']) %>
        </div>
    </div>

     <div style="" class="graph-display">
        <h3>Anotacoes de campo %</h3>
        <div style="", class="graph-and-text">
        <%= pie_chart([
            {name: "Sucesso", data: @player.field_goals_percentage.to_f},
            {name: "Falhados", data: (100 - @player.field_goals_percentage.to_f)},
            ], legend: "left", colors:['#252525', '#3d0000', '#9C27B0']) %>
        </div>
    </div>

    <div style="" class="graph-display">
        <h3>Eficiencia %</h3>
        <div style="", class="graph-and-text">
        <%= pie_chart([
            {name: "Sucesso", data: @player.player_efficiency_rating.to_f},
            {name: "Falhados", data: (100 - @player.player_efficiency_rating.to_f)},
            ], legend: "left", colors:['#252525', '#3d0000', '#9C27B0']) %>
        </div>
    </div>

    <div style="" class="graph-display">
        <h3>Perda de Bola %</h3>
        <div style="", class="graph-and-text">
        <%= pie_chart([
            {name: "Sucesso", data: @player.turn_overs_percentage.to_f},
            {name: "Falhados", data: (100 - @player.turn_overs_percentage.to_f)},
            ], legend: "left", colors:['#252525', '#3d0000', '#9C27B0']) %>
        </div>
    </div>

    <div style="" class="graph-display">
        <h3>Acerto na cesta %</h3>
        <div style="", class="graph-and-text">
        <%= pie_chart([
            {name: "Sucesso", data: @player.true_shooting_percentage.to_f},
            {name: "Falhados", data: (100 - @player.true_shooting_percentage.to_f)},
            ], legend: "left", colors:['#252525', '#3d0000', '#9C27B0']) %>
        </div>
    </div>

     <div style="" class="graph-display">
        <h3>Gols de Campo%</h3>
        <div style="", class="graph-and-text">
        <%= pie_chart([
            {name: "Sucesso", data: @player.effective_field_goals_percentage.to_f},
            {name: "Falhados", data: (100 - @player.effective_field_goals_percentage.to_f)},
            ], legend: "left", colors:['#252525', '#3d0000', '#9C27B0']) %>
        </div>
    </div>

    <div style="" class="graph-display">
        <h3>Rebote%</h3>
        <div style="", class="graph-and-text">
        <%= pie_chart([
            {name: "Sucesso", data: @player.total_rebounds_percentage.to_f},
            {name: "Falhados", data: (100 - @player.total_rebounds_percentage.to_f)},
            ], legend: "left", colors:['#252525', '#3d0000', '#9C27B0']) %>
        </div>
    </div>

</div>
<% end %>

</div>

</section>

